-- JOINS

--01 CROSS JOIN
SELECT * FROM ENGINEER CROSS JOIN TASKS;
-- OR
SELECT * FROM ENGINEER,TASKS;

--02 INNER JOIN
SELECT * FROM ENGINEER
INNER JOIN TASKS ON ENGINEER.ENG_ID = TASKS.ENG_ID;
-- OR
SELECT * FROM ENGINEER E
INNER JOIN TASKS T ON E.ENG_ID = T.ENG_ID;
-- OR
SELECT ENG_NAME, TNAME FROM ENGINEER E
INNER JOIN TASKS T ON E.ENG_ID = T.ENG_ID;

-- O3 LEFT & RIGHT JOIN
--LEFTF
SELECT * FROM ENGINEER E
LEFT JOIN TASKS T ON E.ENG_ID =  T.ENG_ID;

-- RIGHT
SELECT  * FROM ENGINEER E
RIGHT JOIN TASKS T ON E.ENG_ID = T.ENG_ID 

